### ISSUE TITLE
Remove preconditions from docstring parsing (use assert instead)

### ISSUE THREAD

**Issue by fgallaire** [nohtyprm/MrPython#190]
Docstring parsing has many flaws:
- the docstring syntax is a second language to learn (to much for the students, no added value) 
- the syntax is non standard
- the syntax is changing and not documented
- some previously very annoying bugs  
- students have to check bugs in the Python code AND in the docstring

Docstring parsing was previously a must, but PEP 484 and PEP 526 were added to Python and then to MrPython.

The last important usage of the docstring parsing is to check preconditions.

The standard and obvious way to check preconditions is to use `assert`. So we have to remove the MrPython limitation of only use `assert` for testing (outside the functions).

**Comment by fredokun** [comment]
Preconditions and asserts are different things, and preconditions play a significant role in this course (as e.g. loop invariants) as they should play generally in programming language, and both as documentation and if possible runtime checks (at development time)...   Moreover this is no second language to learn since preconditions are parser with the python expression parser, or in case of an error, fallback to just documentation.

The support for precondition checking can be made better of course, but removing preconditions is *not* an option.

**Comment by fgallaire** [comment]
Checking preconditions with `assert` is the de facto standard in the python community, so I don't really understand what is the problem.

**Comment by fredokun** [comment]
there is a difference between a precondition (a logical/conceptual/engineering concept) and an assertion (a source code-level programming artefact). One may check preconditions using assertions, but a precondition is (also) a documentation.   Other related concepts : "invariant", "postcondition"...  cf. Hoare logic for a start.
